// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-projects.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List video projects",
  description: "List the signed-in user's video editing projects, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of projects to return (default 20)."),
    status: z.string().optional().describe("Optional status filter, e.g. draft, ready, exporting.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("video_projects").select("id,title,description,platform,content_type,aspect_ratio,status,duration_seconds,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project details",
  description: "Fetch one of the signed-in user's video projects, including its caption settings and recent edit history.",
  inputSchema: {
    project_id: z2.string().uuid().describe("The project's ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data: project, error } = await supabase.from("video_projects").select("*").eq("id", project_id).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!project) throw new ToolError2("Project not found");
    const { data: edits } = await supabase.from("edit_history").select("id,edit_type,description,parameters,applied_at").eq("project_id", project_id).order("applied_at", { ascending: false }).limit(25);
    const payload = { project, edits: edits ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-video-analysis.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_video_analysis_default = defineTool3({
  name: "get_video_analysis",
  title: "Get video analysis",
  description: "Fetch the AI analysis for a project: transcription, pauses, key moments, scene changes, and suggested edits.",
  inputSchema: {
    project_id: z3.string().uuid().describe("The project's ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("video_analysis").select("*").eq("project_id", project_id).maybeSingle();
    if (error) throw new ToolError3(error.message);
    if (!data) throw new ToolError3("No analysis found for this project yet.");
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { analysis: data }
    };
  }
});

// src/lib/mcp/tools/create-project.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_project_default = defineTool4({
  name: "create_project",
  title: "Create video project",
  description: "Create a new video editing project for the signed-in user. The video file itself is uploaded in the app.",
  inputSchema: {
    title: z4.string().trim().min(1).describe("Project title."),
    description: z4.string().trim().optional().describe("Optional project description or brief."),
    platform: z4.enum(["youtube", "instagram", "tiktok", "twitter", "linkedin", "custom"]).optional().describe("Target platform (default instagram)."),
    content_type: z4.enum(["short", "long"]).optional().describe("Short-form or long-form content."),
    aspect_ratio: z4.enum(["16:9", "9:16", "1:1", "4:5"]).optional().describe("Target aspect ratio.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, platform, content_type, aspect_ratio }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("video_projects").insert({
      user_id: ctx.getUserId(),
      title,
      description: description ?? null,
      platform: platform ?? "instagram",
      content_type: content_type ?? "short",
      aspect_ratio: aspect_ratio ?? "9:16",
      status: "draft"
    }).select().single();
    if (error) throw new ToolError4(error.message);
    return {
      content: [{ type: "text", text: `Created project "${data.title}" (${data.id})` }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/update-project.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var update_project_default = defineTool5({
  name: "update_project",
  title: "Update video project",
  description: "Rename a project or update its description, platform, content type, aspect ratio, or status.",
  inputSchema: {
    project_id: z5.string().uuid().describe("The project's ID."),
    title: z5.string().trim().optional().describe("New project title."),
    description: z5.string().trim().optional().describe("New project description."),
    platform: z5.enum(["youtube", "instagram", "tiktok", "twitter", "linkedin", "custom"]).optional().describe("New target platform."),
    content_type: z5.enum(["short", "long"]).optional().describe("New content type."),
    aspect_ratio: z5.enum(["16:9", "9:16", "1:1", "4:5"]).optional().describe("New aspect ratio."),
    status: z5.string().trim().optional().describe("New project status, e.g. draft or ready.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, ...fields }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const updates = Object.fromEntries(
      Object.entries(fields).filter(([, value]) => value !== void 0)
    );
    if (Object.keys(updates).length === 0) throw new ToolError5("Provide at least one field to update.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("video_projects").update({ ...updates, updated_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", project_id).select().maybeSingle();
    if (error) throw new ToolError5(error.message);
    if (!data) throw new ToolError5("Project not found");
    return {
      content: [{ type: "text", text: `Updated project "${data.title}" (${data.id})` }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/delete-project.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var delete_project_default = defineTool6({
  name: "delete_project",
  title: "Delete video project",
  description: "Permanently delete one of the signed-in user's projects along with its analysis and edit history.",
  inputSchema: {
    project_id: z6.string().uuid().describe("The project's ID.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError6("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data: project, error: findError } = await supabase.from("video_projects").select("id,title").eq("id", project_id).maybeSingle();
    if (findError) throw new ToolError6(findError.message);
    if (!project) throw new ToolError6("Project not found");
    await supabase.from("edit_history").delete().eq("project_id", project_id);
    await supabase.from("video_analysis").delete().eq("project_id", project_id);
    const { error } = await supabase.from("video_projects").delete().eq("id", project_id);
    if (error) throw new ToolError6(error.message);
    return {
      content: [{ type: "text", text: `Deleted project "${project.title}" (${project.id})` }],
      structuredContent: { deleted_project_id: project.id }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bkhdorwhekifuapiisxk";
var mcp_default = defineMcp({
  name: "chat-edit-pro",
  title: "Chat Edit Pro",
  version: "0.1.0",
  instructions: "Tools for Chat Edit Pro, an AI video editing app. Use `list_projects` and `get_project` to inspect the signed-in user's video projects, `get_video_analysis` to read a project's transcript, pauses, key moments and suggested edits, and `create_project` / `update_project` / `delete_project` to manage projects. Video uploads, rendering, and export happen inside the app.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_projects_default,
    get_project_default,
    get_video_analysis_default,
    create_project_default,
    update_project_default,
    delete_project_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
